[project]
name = "diff-csv-schemas"
version = "0.1.0"
description = "Three ways to merge CSV files with slightly different schemas."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.2",
    "pandas>=2.3.3",
    "polars>=1.35.2",
]
